### ISSUE TITLE
No input on host (Linux)

### ISSUE THREAD

**Issue by parkerlreed** [Frederic98/SteamDeckGadget#3]
I have loaded your script as per the instructions with no errors. 

Shows up on Arch Linux host machine as controller but none of the inputs are coming through.

I have tried with Steam running, Steam shut down, and hid_steam unloaded on the Deck with the same result.

**Comment by parkerlreed** [comment]
Ran it manually after adding to Steam and I get this

```
(deck@steamdeck SteamDeckGadget)$ ./run_ui 
steam.sh[3983]: Running Steam on steamos rolling 64-bit
steam.sh[3983]: STEAM_RUNTIME is enabled automatically
setup.sh[4061]: Steam runtime environment up-to-date!
steam.sh[3983]: Steam client's requirements are satisfied
[S_API] SteamAPI_Init(): Loaded '/home/deck/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 480
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198003387494 [API loaded no]
Exception in thread Thread-1 (steam_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/deck/build/SteamDeckGadget/main.py", line 46, in steam_worker
    self.window.update_information(data)
  File "/home/deck/build/SteamDeckGadget/joystick_ui.py", line 37, in update_information
    self._update_info_signal.emit(self.data)
RuntimeError: wrapped C/C++ object of type JoystickUI has been deleted
steam.sh[4127]: Running Steam on steamos rolling 64-bit
steam.sh[4127]: STEAM_RUNTIME is enabled automatically
setup.sh[4205]: Steam runtime environment up-to-date!
steam.sh[4127]: Steam client's requirements are satisfied
```

Controller ID shows up in the GUI but that's it. No movement client or host aside.

**Comment by Frederic98** [comment]
That traceback is from exiting the application, complaining that the UI has already closed but it's still trying to do some stuff with it. Can ignore that for now.

I missed something in the README, added it now (cfc94d9). You have to map the Deck inputs to game actions manually because this is not a game released through steam.
